---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: assisted-events-stream-projection
parameters:
- name: REPLICAS_COUNT
  value: "1"
- name: IMAGE_NAME
  value: "quay.io/edge-infrastructure/assisted-events-stream"
- name: IMAGE_TAG
  value: ""
  required: true
- name: CPU_LIMIT
  value: "1"
- name: CPU_REQUEST
  value: "10m"
- name: MEMORY_LIMIT
  value: "512Mi"
- name: MEMORY_REQUEST
  value: "256Mi"
- name: NAMESPACE
  value: assisted-events-streams
- name: KAFKA_EVENT_STREAM_TOPIC
  value: "events-stream-integration"
- name: KAFKA_GROUP_ID
  value: "enriched-event-projection"
- name: REDIS_ADDRESS
  value: "assisted-events-streams-redis:6379"
- name: REDIS_CREDENTIALS_SECRETNAME
  value: redis-credentials
- name: OPENSEARCH_CREDENTIALS_SECRETNAME
  value: elastic-master-credentials
- name: OPENSEARCH_ENDPOINT_SECRETNAME
  value: assisted-installer-elasticsearch
- name: OPENSEARCH_INDEX_PREFIX
  value: assisted-installer-events-v1-
- name: OPENSEARCH_CONFIG_INDEX
  value: "config"
- name: OPENSEARCH_BULK_WORKERS
  value: "1"
- name: OPENSEARCH_BULK_FLUSH_BYTES
  value: "10000000"
- name: OPENSEARCH_BULK_FLUSH_INTERVAL
  value: "120s"
- name: OPENSEARCH_RESPONSE_TIMEOUT
  value: "90s"
- name: OPENSEARCH_SSL_INSECURE_SKIP_VERIFY
  value: "false"
- name: KAFKA_CREDENTIALS_SECRETNAME
  value: assisted-installer-event-stream
- name: KAFKA_SASL_MECHANISM
  value: "PLAIN"
- name: LOG_LEVEL
  value: info
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: enriched-event-projection
  spec:
    selector:
      matchLabels:
          app.kubernetes.io/name: enriched-event-projection
    replicas: ${{REPLICAS_COUNT}}
    template:
      metadata:
        labels:
          app.kubernetes.io/name: enriched-event-projection
      spec:
        containers:
        - name: projection
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          imagePullPolicy: ${IMAGE_PULL_POLICY}
          command:
          - /projection
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
          env:            
          - name: OPENSEARCH_CONFIG_INDEX
            value: ${OPENSEARCH_CONFIG_INDEX}
          - name: OPENSEARCH_BULK_WORKERS
            value: ${OPENSEARCH_BULK_WORKERS}
          - name: OPENSEARCH_BULK_FLUSH_BYTES
            value: ${OPENSEARCH_BULK_FLUSH_BYTES}
          - name: OPENSEARCH_BULK_FLUSH_INTERVAL
            value: ${OPENSEARCH_BULK_FLUSH_INTERVAL}
          - name: OPENSEARCH_RESPONSE_TIMEOUT
            value: ${OPENSEARCH_RESPONSE_TIMEOUT}
          - name: OPENSEARCH_SSL_INSECURE_SKIP_VERIFY
            value: ${OPENSEARCH_SSL_INSECURE_SKIP_VERIFY}
          - name: KAFKA_EVENT_STREAM_TOPIC
            value: ${KAFKA_EVENT_STREAM_TOPIC}
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: KAFKA_GROUP_ID
            value: ${KAFKA_GROUP_ID}
          - name: KAFKA_SASL_MECHANISM
            value: ${KAFKA_SASL_MECHANISM}
          - name: KAFKA_BOOTSTRAP_SERVER
            valueFrom:
              secretKeyRef:
                name: ${KAFKA_CREDENTIALS_SECRETNAME}
                key: bootstrap_server_host
          - name: KAFKA_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: ${KAFKA_CREDENTIALS_SECRETNAME}
                key: client_id
          - name: KAFKA_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: ${KAFKA_CREDENTIALS_SECRETNAME}
                key: client_secret
          - name: REDIS_ADDRESS
            value: ${REDIS_ADDRESS}
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${REDIS_CREDENTIALS_SECRETNAME}
                key: password
          - name: OPENSEARCH_INDEX_PREFIX
            value: "${OPENSEARCH_INDEX_PREFIX}"
          - name: OPENSEARCH_ADDRESS
            valueFrom:
              secretKeyRef:
                key: endpoint
                name: ${OPENSEARCH_ENDPOINT_SECRETNAME}
          - name: OPENSEARCH_USERNAME
            valueFrom:
              secretKeyRef:
                key: master_user_name
                name: ${OPENSEARCH_CREDENTIALS_SECRETNAME}
          - name: OPENSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                key: master_user_password
                name: ${OPENSEARCH_CREDENTIALS_SECRETNAME}
